#item['country'] = row.xpath('./td[contains(@headers, "COUNTRY_NAME")]/text()').extract_first()
 #           item['foreign_principal'] = row.xpath('./td[contains(@headers, "FP_NAME")]/text()').extract_first()
  #          item['foreign_principal_reg_date'] = row.xpath('./td[contains(@headers, "FP_REG_DATE")]/text()').extract_first()
   #         item['address'] = row.xpath('./td[contains(@headers, "ADDRESS_1")]/text()').extract_first()
    #       item['registrant'] = row.xpath('./td[contains(@headers, "REGISTRANT_NAME")]/text()').extract_first()
     #       item['reg_num'] = row.xpath('./td[contains(@headers, "REG_NUMBER")]/text()').extract_first()
      #      item['reg_date'] = row.xpath('./td[contains(@headers, "REG_DATE")]/text()').extract_first()